---
title: "Replication of 'Induction and Relief of Curiosity Elicit Parietal and Frontal Activity'"
output: html_notebook
---

#### Task Authors
*Anthony Haffey, Kristian Tempelmans Plat, Nicolo Biagi (Scientific Open Solutions)*


## Introduction

This study was based on Lieshout et al's 2018 fMRI study found at: https://www.jneurosci.org/content/38/10/2579


## Methods
We took some methodological decisions when creating this task:

- We thought that a pseudorandomised trial order would be helpful for capturing individual differences
- This means that half of participants would complete a pseudorandomised order and the other half would complete this order in reverse
- All aspects of the task were controlled by a spreadsheet (see "Order1.csv" and "Order2.csv"), and there was no randomisation outside of this spreadsheet
- Each participant received:
  - 10 trials with all the marbles as red, seeing the result
  - 10 trials with all the marbles as blue, seeing the result
  - 10 trials with all the marbles as red, **NOT** seeing the result
  - 10 trials with all the marbles as blue, **NOT** seeing the result
- more details here



